var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_GAMEOVER = "GAME OVER";
var TEXT_ARE_SURE = "ARE YOU SURE YOU WANT TO QUIT THE GAME?";
var TEXT_SAVE_REMOVE = "THIS WILL REMOVE ALL YOUR ACHIEVEMENTS! DO YOU WANT TO PROCEED?"
var TEXT_TOTAL_SCORE = "TOTAL SCORE";
var TEXT_LAUNCH = "LAUNCH";
var TEXT_HOLE = "HOLE";
var TEXT_LOADING = "LOADING...";
var TEXT_ALL_COMPLETE = "ALL LEVEL COMPLETED";
var TEXT_SELECT_A_LEVEL = "SELECT A LEVEL";
var TEXT_HELP1_PC = "CLICK THE BALL AND DRAG TO SET POWER AND DIRECTION";
var TEXT_HELP1_MOBILE = "TOUCH THE BALL AND DRAG THE FINGER TO SET POWER AND DIRECTION";
var TEXT_HELP2 = "CLICK AND DRAG TO HAVE A PAN VIEW";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";

var TEXT_SCORE = "SCORE";
var TEXT_COMPLETE = "COMPLETE";

var TEXT_DEVELOPED = "DEVELOPED BY";

var TEXT_DOUBLE_BOGEY = "DOUBLE BOGEY";
var TEXT_BOGEY = "BOGEY";
var TEXT_PAR = "PAR";
var TEXT_BIRDIE = "BIRDIE";
var TEXT_EAGLE = "EAGLE";
var TEXT_ALBATROSS = "ALBATROSS";
var TEXT_CONDOR = "CONDOR";
var TEXT_PHOENIX = "PHOENIX";
var TEXT_HOLEINONE = "HOLE IN ONE";


var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better?";