var CANVAS_WIDTH = 1600;
var CANVAS_HEIGHT = 968;

var EDGEBOARD_X = 150;
var EDGEBOARD_Y = 150;

var DISABLE_SOUND_MOBILE = false;
var PRIMARY_FONT = "space_comics";

var FPS = 60;
var FPS_TIME = 1000 / FPS;

var STATE_LOADING = 0;
var STATE_MENU = 1;
var STATE_HELP = 1;
var STATE_GAME = 3;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END = 5;
var ON_CONTROLLER_END    = 8;
var ON_CONTROLLER_REMOVE = 9;
var ON_CONTROLLER_ROLL = 10;

var RESTART_WATER_DEPTH_VALUE = 5;
var HOLE_DEPTH_VALUE = 3;

var MIN_MOUSE_DISTANCE_POWER_ACTIVATED = 30;
var MIN_MOUSE_DISTANCE_POWER_ACTIVATED_MOBILE = 100;
var MAX_MOUSE_DISTANCE_POWER_ACTIVATED = 300;


var BALL_MASS = 1;
var BALL_RADIUS = 2;
var BALL_FRICTION = 0.5;
var BALL_RESTITUTION = 0.5;
var BALL_LINEAR_DAMPING = 0.5;
var BALL_LINEAR_DAMPING_SAND = 0.95;
var BALL_LINEAR_DAMPING_WATER = 0.99;
var BALL_LINEAR_DAMPING_HOLE = 3.8;

var MIN_VELOCITY_FOR_LAUNCH = 1.5;

var ARROW_DISTANCE = 75;
var RATIO_ARROW_DISTANCE = 4;
var TIME_FOR_LAUNCH = 0.2;
var OFFSET_ANGLE_ARROW = 90;

var HIT_BALL_MAX_FORCE = 200;
var HIT_BALL_MIN_FORCE = 0.01;

var SHOW_3D_RENDER = false;
var CAMERA_TEST = false;

var START_CAMERA_POSITION = {x: -240, y: -290, z: 280};
var NEAR = -30, FAR = 2000;

var FORCE_MULTIPLIER = 2;


var PAR_POINTS;
var ADDED_POINTS;
var MAX_SHOT_POWER;
var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;
